// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbA9Y3ye-2gJR0jI3yQpDBRPlwAW-gKNc',
    appId: '1:553891451539:web:ecdd3166b3c67344eb7366',
    messagingSenderId: '553891451539',
    projectId: 'ambulatec-6d892',
    authDomain: 'ambulatec-6d892.firebaseapp.com',
    storageBucket: 'ambulatec-6d892.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASswvWrlThkkLPD7p_OXJ2oCO-fg-kdZk',
    appId: '1:553891451539:android:a63fcf1e2addd112eb7366',
    messagingSenderId: '553891451539',
    projectId: 'ambulatec-6d892',
    storageBucket: 'ambulatec-6d892.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9M5-ZqAId6bWxCoz5KBNJfQTyfRQSazU',
    appId: '1:553891451539:ios:b1dcec0dbf9141d5eb7366',
    messagingSenderId: '553891451539',
    projectId: 'ambulatec-6d892',
    storageBucket: 'ambulatec-6d892.firebasestorage.app',
    iosClientId: '553891451539-hmjov32jnpneg1iqjj8tmi3dbon7ast6.apps.googleusercontent.com',
    iosBundleId: 'com.teccelaya.ambulatec',
  );
}
